language: node_js

node_js:
  - "6"

script:
  - npm test

after_success:
  - npm run version && npm build

env:
  global:
    - BLUEMIX_SPACE="ToddsPlace" BLUEMIX_ORG="ToddTown"
  matrix:

deploy:
  - deploy:
    provider: bluemixcf
    skip_cleanup: true
    edge:
      source: adamkingit/dpl
      branch: master
    manifest: manifest-uk-stage.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    region:   eu-gb
    organization: $BLUEMIX_ORG
    space: $BLUEMIX_SPACE
    on:
      branch: staging
